[package]
name = "autopilot_wrapper"
version = "0.1.0"
authors = ["Logarithmus <logarithmus.dev@gmail.com>"]
edition = "2018"

[lib]
name = "autopilot_wrapper"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.4.0"
image = "0.22.4"
autopilot = "0.4.0"
clipboard = "0.5.0"
